config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do
  resource :example, constraints: -> { Rails.env.development? }
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks",
    passwords: "users/passwords"
  }

  devise_scope :user do
    get "users/email_lookup", to: "users/registrations#email_lookup", as: :users_email_lookup
    get "users/mobile_lookup", to: "users/registrations#mobile_lookup", as: :users_mobile_lookup
    get "users/password/mobile/verify", to: "users/passwords#verify_mobile", as: :verify_user_password_mobile
    post "users/password/mobile/confirm", to: "users/passwords#confirm_mobile", as: :confirm_user_password_mobile
    post "users/password/mobile/resend", to: "users/passwords#resend_mobile", as: :resend_user_password_mobile
  end

  namespace :users do
    resource :mobile_verification, only: %i[new create], controller: "mobile_verifications" do
      get :verify
      post :confirm
      post :resend
    end
  end

  match "/google-auth/success",
        to: "users/omniauth_callbacks#google_oauth2",
        via: %i[get post],
        as: :google_oauth2_callback

  get "up" => "rails/health#show", as: :rails_health_check

  scope module: :public, as: :public do
    resources :clubs, only: %i[index show], path: "clubs"
  end

  namespace :club do
    resource :dashboard, only: :show

    resources :members do
      resources :consents, only: %i[index new create]
    end

    resources :consent_types, only: :index

    resources :invoices, only: %i[index show] do
      post :pay, on: :member
      get :download, on: :member
    end

    resources :teams do
      get :squad, on: :member
      get :match_sheet, on: :member
      resources :fixtures, only: %i[index create]
    end

    resources :fixtures, only: %i[show update] do
      patch :availability, on: :member
    end

    resources :broadcasts, only: %i[index new create show]

    resources :reports, only: :index do
      collection do
        get :finance
        get :participation
        get :compliance
        get :ar_aging
      end
    end
    resources :plans, only: :index
    root "dashboard"
  end

  namespace :admin do
    mount Sidekiq::Web => "/sidekiq" # access it at http://localhost:3000/sidekiq
    resource :dashboard, only: :show
    resources :clubs do
      post :impersonate, on: :member
      patch :remove_file, on: :member
      resources :membership_types,
                module: :clubs,
                except: %i[index] do
        resources :price_tiers,
                  module: :membership_types,
                  except: %i[index show]
      end
      resources :default_price_tiers,
                module: :clubs,
                except: %i[index]
      resources :membership_questions,
                module: :clubs,
                except: %i[index]
      resources :medical_questions,
                module: :clubs,
                except: %i[index] do
        patch :toggle, on: :member
      end
      resources :terms,
                module: :clubs,
                except: %i[index]
      resources :staggered_payment_plans,
                module: :clubs,
                except: %i[index show]
      resources :memberships,
                module: :clubs,
                only: %i[index show]
    end
    resources :users
    resources :members, only: %i[index show]
    resources :orders, only: %i[index show]

    resources :invoices, only: %i[index show] do
      collection { get :reconciliation }
    end

    resources :broadcasts, only: %i[index show update] do
      post :approve, on: :member
    end

    resources :audits, only: :index
    resources :retention_jobs, only: %i[index create]

    namespace :webhooks do
      resources :payments, only: :create
      resources :whatsapp, only: :create
    end

    root "dashboard"
  end

  namespace :members do
    resource :selection, only: :new do
      get :search
    end
    resource :dashboards
    get "" => "dashboards#index"
    resource :membership_registration, only: %i[show update]
    resource :cart, only: :show do
      resources :items, controller: "cart_items", only: %i[create update destroy]
    end
    resource :checkout, only: :create
    resources :payment_methods, only: :destroy
    resources :orders, only: :show
    get "checkout/success", to: "checkouts#success", as: :checkout_success
    get "checkout/failure", to: "checkouts#failure", as: :checkout_failure
  end

  root "members/dashboards#index"
end

app/controllers/admin/clubs/default_price_tiers_controller.rb
# frozen_string_literal: true

class Admin::Clubs::DefaultPriceTiersController < Admin::BaseController
  include ActionView::RecordIdentifier

  before_action :set_club
  before_action :set_default_price_tier, only: %i[show edit update destroy]

  def new
    @default_price_tier = @club.default_price_tiers.build
    authorize! @default_price_tier
    frame_id = frame_identifier(params[:frame_id])

    if params[:reset].present?
      render partial: "admin/clubs/default_price_tiers/new_button", locals: { club: @club }
    else
      render partial: "admin/clubs/default_price_tiers/form",
             locals: { club: @club, default_price_tier: @default_price_tier, frame_id: frame_id }
    end
  end

  def create
    @default_price_tier = @club.default_price_tiers.build(default_price_tier_params)
    authorize! @default_price_tier

    if @default_price_tier.save
      @default_price_tiers = default_price_tiers_scope
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.replace(
              dom_id(@club, :default_price_tiers),
              partial: "admin/clubs/default_price_tiers/list",
              locals: { club: @club, default_price_tiers: @default_price_tiers }
            ),
            turbo_stream.replace(
              dom_id(@club, :new_default_price_tier),
              partial: "admin/clubs/default_price_tiers/new_button",
              locals: { club: @club }
            )
          ]
        end
        format.html { redirect_to admin_club_path(@club), notice: "Default tier added." }
      end
    else
      render_form_failure
    end
  end

  def show
    authorize! @default_price_tier
    render partial: "admin/clubs/default_price_tiers/default_price_tier",
           locals: { club: @club, default_price_tier: @default_price_tier }
  end

  def edit
    authorize! @default_price_tier
    render partial: "admin/clubs/default_price_tiers/form",
           locals: { club: @club, default_price_tier: @default_price_tier, frame_id: frame_identifier(params[:frame_id]) }
  end

  def update
    authorize! @default_price_tier
    if @default_price_tier.update(default_price_tier_params)
      @default_price_tiers = default_price_tiers_scope
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(
            dom_id(@club, :default_price_tiers),
            partial: "admin/clubs/default_price_tiers/list",
            locals: { club: @club, default_price_tiers: @default_price_tiers }
          )
        end
        format.html { redirect_to admin_club_path(@club), notice: "Default tier updated." }
      end
    else
      render_form_failure
    end
  end

  def destroy
    authorize! @default_price_tier
    @default_price_tier.destroy
    @default_price_tiers = default_price_tiers_scope

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.remove(@default_price_tier),
          turbo_stream.replace(
            dom_id(@club, :default_price_tiers),
            partial: "admin/clubs/default_price_tiers/list",
            locals: { club: @club, default_price_tiers: @default_price_tiers }
          ),
          turbo_stream.replace(
            dom_id(@club, :new_default_price_tier),
            partial: "admin/clubs/default_price_tiers/new_button",
            locals: { club: @club }
          )
        ]
      end
      format.html { redirect_to admin_club_path(@club), notice: "Default tier removed." }
    end
  end

  private

  def set_club
    @club = Club.find(params[:club_id])
    authorize! @club, to: :update?
  end

  def set_default_price_tier
    @default_price_tier = @club.default_price_tiers.find(params[:id])
  end

  def default_price_tier_params
    params.require(:club_default_price_tier).permit(:label, :starts_on, :ends_on)
  end

  def default_price_tiers_scope
    @club.default_price_tiers.ordered
  end

  def render_form_failure
    respond_to do |format|
      format.turbo_stream do
        render partial: "admin/clubs/default_price_tiers/form",
               locals: {
                 club: @club,
                 default_price_tier: @default_price_tier,
                 frame_id: frame_identifier(params[:frame_id])
               },
               status: :unprocessable_entity
      end
      format.html do
        @default_price_tiers = default_price_tiers_scope
        render "admin/clubs/show", status: :unprocessable_entity
      end
    end
  end

  def frame_identifier(fallback = nil)
    fallback.presence || request.headers["Turbo-Frame"] || dom_id(@club, :default_price_tier_modal)
  end
end

app/controllers/admin/clubs/medical_questions_controller.rb
# frozen_string_literal: true

class Admin::Clubs::MedicalQuestionsController < Admin::BaseController
  include ActionView::RecordIdentifier

  before_action :set_club
  before_action :set_medical_question, only: %i[show edit update destroy toggle]

  def new
    @medical_question = @club.medical_questions.build
    authorize! @medical_question
    frame_id = frame_identifier(params[:frame_id])

    if params[:reset].present?
      render partial: "admin/clubs/medical_questions/new_button", locals: { club: @club }
    else
      render partial: "admin/clubs/medical_questions/form",
             locals: { club: @club, medical_question: @medical_question, frame_id: frame_id }
    end
  end

  def create
    @medical_question = @club.medical_questions.build(medical_question_params)
    authorize! @medical_question

    if @medical_question.save
      @medical_questions = medical_questions_scope
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.replace(
              dom_id(@club, :medical_questions),
              partial: "admin/clubs/medical_questions/list",
              locals: { club: @club, medical_questions: @medical_questions }
            ),
            turbo_stream.replace(
              dom_id(@club, :new_medical_question),
              partial: "admin/clubs/medical_questions/new_button",
              locals: { club: @club }
            )
          ]
        end
        format.html { redirect_to admin_club_path(@club), notice: "Medical question added." }
      end
    else
      render_form_failure
    end
  end

  def show
    authorize! @medical_question
    render partial: "admin/clubs/medical_questions/question",
           locals: { club: @club, medical_question: @medical_question }
  end

  def edit
    authorize! @medical_question
    render partial: "admin/clubs/medical_questions/form",
           locals: { club: @club, medical_question: @medical_question, frame_id: frame_identifier(params[:frame_id]) }
  end

  def update
    authorize! @medical_question
    if @medical_question.update(medical_question_params)
      @medical_questions = medical_questions_scope
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(
            dom_id(@club, :medical_questions),
            partial: "admin/clubs/medical_questions/list",
            locals: { club: @club, medical_questions: @medical_questions }
          )
        end
        format.html { redirect_to admin_club_path(@club), notice: "Medical question updated." }
      end
    else
      render_form_failure
    end
  end

  def destroy
    authorize! @medical_question
    @medical_question.destroy
    @medical_questions = medical_questions_scope

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.remove(@medical_question),
          turbo_stream.replace(
            dom_id(@club, :medical_questions),
            partial: "admin/clubs/medical_questions/list",
            locals: { club: @club, medical_questions: @medical_questions }
          ),
          turbo_stream.replace(
            dom_id(@club, :new_medical_question),
            partial: "admin/clubs/medical_questions/new_button",
            locals: { club: @club }
          )
        ]
      end
      format.html { redirect_to admin_club_path(@club), notice: "Medical question removed." }
    end
  end

  def toggle
    authorize! @medical_question, to: :toggle?
    @medical_question.update!(active: !@medical_question.active?)
    @medical_questions = medical_questions_scope

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(
          dom_id(@club, :medical_questions),
          partial: "admin/clubs/medical_questions/list",
          locals: { club: @club, medical_questions: @medical_questions }
        )
      end
      format.html do
        notice = @medical_question.active? ? "Question activated." : "Question hidden."
        redirect_to admin_club_path(@club), notice: notice
      end
    end
  end


  def set_club
    @club = Club.find(params[:club_id])
    authorize! @club, to: :update?
  end

  def set_medical_question
    @medical_question = @club.medical_questions.find(params[:id])
  end
  private

  def medical_question_params
    params.require(:medical_question).permit(:prompt, :question_type, :position, :active, :required)
  end

  def medical_questions_scope
    @club.medical_questions.order(:position, :created_at)
  end

  def render_form_failure
    respond_to do |format|
      format.turbo_stream do
        render partial: "admin/clubs/medical_questions/form",
               locals: {
                 club: @club,
                 medical_question: @medical_question,
                 frame_id: frame_identifier(params[:frame_id])
               },
               status: :unprocessable_entity
      end
      format.html do
        @medical_questions = medical_questions_scope
        @default_price_tiers = @club.default_price_tiers.ordered
        render "admin/clubs/show", status: :unprocessable_entity
      end
    end
  end

  def frame_identifier(fallback = nil)
    fallback.presence || request.headers["Turbo-Frame"] || dom_id(@club, :medical_question_modal)
  end
end

app/controllers/admin/clubs/memberships_controller.rb
# frozen_string_literal: true

class Admin::Clubs::MembershipsController < Admin::BaseController
  before_action :set_club
  before_action :set_membership, only: :show

  def index
    authorize! Order, :index?
    @purchases = OrderItem
                   .includes(:member, plan: :product, order: :payment_method)
                   .joins(:order)
                   .where(orders: { club_id: @club.id })
                   .order("order_items.created_at DESC")
  end

  def show
    authorize! @order
    @transactions = @order.payment_transactions.includes(:payment_method).order(processed_at: :desc, created_at: :desc)
    @guardians = @member&.guardianships&.includes(:guardian) || []
    @question_responses = @member&.membership_question_responses&.includes(:membership_question) || []
  end

  private

  def set_club
    @club = Club.find(params[:club_id])
    authorize! @club, :update?
  end

  def set_membership
    @order_item = OrderItem
                    .includes(:member, plan: :product, order: :payment_method)
                    .joins(:order)
                    .where(orders: { club_id: @club.id })
                    .find(params[:id])
    @order = @order_item.order
    @member = @order_item.member
  end
end

app/controllers/club/base_controller.rb
# frozen_string_literal: true

class Club::BaseController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_club_context
  helper_method :current_cart, :manageable_members

  private

  def ensure_club_context
    return if current_club.present?

    redirect_to new_user_session_path, alert: "We couldn't determine your club. Please sign in again."
  end

  def current_cart
    @current_cart ||= begin
      Cart.unpaid.find_by(user: current_user, club: current_club) ||
        Cart.create!(user: current_user, club: current_club)
    end
  end

  def manageable_members
    return Member.none unless current_user && current_club

    member_ids = current_user.members.where(club: current_club).pluck(:id)
    guardian_ids = current_user.guarded_members.where(club: current_club).pluck(:id)
    ids = (member_ids + guardian_ids).uniq

    return Member.none if ids.empty?

    policy_scope(Member).where(id: ids).includes(:club).order(:last_name, :first_name)
  end
end

app/controllers/club/consent_types_controller.rb
# frozen_string_literal: true

class Club::ConsentTypesController < Club::BaseController
  def index
    @consent_types = policy_scope(ConsentType).order(:key)
    authorize! ConsentType, :index?
  end
end

app/controllers/club/dashboard_controller.rb
# frozen_string_literal: true

class Club::DashboardController < Club::BaseController
  def show
    authorize! current_club, :show?

    direct_members = current_user.members.includes(:club)
    guardian_members = current_user.guarded_members.includes(:club)

    @membership_profiles = (direct_members.to_a + guardian_members.to_a).uniq { |member| member.id }
    @known_clubs = (@membership_profiles.map(&:club) + current_user.clubs.to_a).compact.uniq { |club| club.id }
  end
end

app/views/admin/clubs/terms/_form.html.erb
<% frame_dom_id = local_assigns[:frame_id] || (term.persisted? ? dom_id(term) : dom_id(club, :new_club_term)) %>
<% form_url = term.persisted? ? admin_club_term_path(club, term) : admin_club_terms_path(club) %>

<%= turbo_frame_tag frame_dom_id do %>
  <%= form_with model: term, url: form_url, class: "space-y-4" do |form| %>
    <% if term.errors.any? %>
      <div class="rounded border border-rose-200 bg-rose-50 px-3 py-2 text-sm text-rose-700">
        <%= term.errors.full_messages.to_sentence %>
      </div>
    <% end %>

    <div class="space-y-1">
      <%= form.label :title, "Title", class: "block text-sm font-medium text-slate-700" %>
      <%= form.text_field :title,
        class: "w-full rounded border border-slate-300 px-3 py-2 text-sm focus:border-slate-500 focus:outline-none focus:ring",
        placeholder: "e.g. Code of conduct" %>
    </div>

    <div class="space-y-1">
      <%= form.label :body, "Term content", class: "block text-sm font-medium text-slate-700" %>
      <%= form.text_area :body,
        rows: 4,
        class: "w-full rounded border border-slate-300 px-3 py-2 text-sm focus:border-slate-500 focus:outline-none focus:ring",
        placeholder: "Describe the requirement members must agree to." %>
    </div>

    <div class="grid gap-4 md:grid-cols-2">
      <div class="space-y-1">
        <%= form.label :position, "Display order", class: "block text-sm font-medium text-slate-700" %>
        <%= form.number_field :position,
          min: 0,
          class: "w-full rounded border border-slate-300 px-3 py-2 text-sm focus:border-slate-500 focus:outline-none focus:ring" %>
      </div>
      <div class="space-y-1">
        <%= form.label :required, "Required to proceed", class: "block text-sm font-medium text-slate-700" %>
        <div class="flex items-center gap-2">
          <%= form.check_box :required, class: "rounded border-slate-300 text-slate-900 focus:ring-slate-500" %>
          <span class="text-sm text-slate-600">Members must accept</span>
        </div>
      </div>
    </div>

    <div class="flex items-center gap-2">
      <%= form.check_box :active, class: "rounded border-slate-300 text-slate-900 focus:ring-slate-500" %>
      <%= form.label :active, "Visible during registration", class: "text-sm text-slate-600" %>
    </div>

    <div class="flex items-center justify-end gap-3">
      <% if term.persisted? %>
        <%= link_to "Cancel",
          admin_club_term_path(club, term),
          data: { turbo_frame: dom_id(term) },
          class: "text-sm font-medium text-slate-500 hover:text-slate-700" %>
      <% else %>
        <button
          type="button"
          class="text-sm font-medium text-slate-500 hover:text-slate-700"
          data-action="modal#close"
        >
          Cancel
        </button>
      <% end %>
      <%= form.submit(term.persisted? ? "Save changes" : "Create term",
        class: "inline-flex items-center rounded bg-slate-900 px-4 py-2 text-sm font-medium text-white hover:bg-slate-800") %>
    </div>
  <% end %>
<% end %>

app/views/admin/clubs/terms/_list.html.erb
<% if terms.any? %>
  <div class="divide-y divide-slate-200">
    <% terms.each_with_index do |term, index| %>
      <%= render "admin/clubs/terms/term",
                 club: club,
                 term: term,
                 index: index + 1 %>
    <% end %>
  </div>
<% else %>
  <div class="px-4 py-10 text-center text-sm text-slate-500">
    <p class="font-medium text-slate-700">No terms yet</p>
    <p class="mt-1 text-xs text-slate-500">Add club-specific terms and conditions for members to accept during registration.</p>
  </div>
<% end %>

app/views/admin/clubs/terms/_new_button.html.erb
<div class="flex justify-end">
  <button
    type="button"
    data-action="modal#open"
    data-modal-url="<%= new_admin_club_term_path(club) %>"
    data-modal-frame="<%= dom_id(club, :club_term_modal) %>"
    data-modal-title="Add term"
    class="inline-flex items-center gap-2 rounded bg-slate-900 px-3 py-2 text-sm font-medium text-white transition hover:bg-slate-800"
  >
    <span class="inline-flex h-5 w-5 items-center justify-center rounded-full bg-white/10 text-base leading-none">+</span>
    Add term
  </button>
</div>

app/views/admin/clubs/terms/_term.html.erb
<turbo-frame id="<%= dom_id(term) %>">
  <article class="flex flex-col gap-4 px-4 py-4 transition hover:bg-slate-50 md:flex-row md:items-start md:justify-between">
    <div class="space-y-3">
      <div class="flex flex-wrap items-center gap-2 text-xs font-medium uppercase tracking-wide text-slate-400">
        <span>Term <%= index || "?" %></span>
        <span class="inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[11px] font-semibold <%= term.required? ? "bg-emerald-100 text-emerald-700" : "bg-slate-100 text-slate-600" %>">
          <%= term.required? ? "Required" : "Optional" %>
        </span>
        <span class="inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[11px] font-semibold <%= term.active? ? "bg-sky-100 text-sky-700" : "bg-slate-100 text-slate-500" %>">
          <%= term.active? ? "Visible" : "Hidden" %>
        </span>
      </div>
      <div class="space-y-2">
        <h3 class="text-sm font-semibold text-slate-900"><%= term.title %></h3>
        <div class="max-h-48 overflow-y-auto rounded border border-slate-100 bg-slate-50 px-3 py-2">
          <div class="prose prose-sm max-w-none text-slate-700">
            <%= simple_format(term.body) %>
          </div>
        </div>
      </div>
    </div>

    <div class="flex items-center gap-2 md:flex-col md:items-end">
      <button
        type="button"
        class="inline-flex items-center gap-1 rounded border border-slate-300 px-3 py-1.5 text-sm font-medium text-slate-700 transition hover:bg-slate-100"
        data-action="modal#open"
        data-modal-url="<%= edit_admin_club_term_path(club, term) %>"
        data-modal-frame="<%= dom_id(club, :club_term_modal) %>"
        data-modal-title="Edit term"
      >
        Edit
      </button>
      <%= link_to "Delete",
                  admin_club_term_path(club, term),
                  data: {
                    turbo_method: :delete,
                    turbo_confirm: "Delete this term?",
                    turbo_frame: dom_id(club, :club_terms)
                  },
                  class: "inline-flex items-center gap-1 rounded bg-rose-50 px-3 py-1.5 text-sm font-medium text-rose-600 transition hover:bg-rose-100" %>
    </div>
  </article>
</turbo-frame>