config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do
  resource :example, constraints: -> { Rails.env.development? }
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks",
    passwords: "users/passwords"
  }

  devise_scope :user do
    get "users/email_lookup", to: "users/registrations#email_lookup", as: :users_email_lookup
    get "users/mobile_lookup", to: "users/registrations#mobile_lookup", as: :users_mobile_lookup
    get "users/password/mobile/verify", to: "users/passwords#verify_mobile", as: :verify_user_password_mobile
    post "users/password/mobile/confirm", to: "users/passwords#confirm_mobile", as: :confirm_user_password_mobile
    post "users/password/mobile/resend", to: "users/passwords#resend_mobile", as: :resend_user_password_mobile
  end

  namespace :users do
    resource :mobile_verification, only: %i[new create], controller: "mobile_verifications" do
      get :verify
      post :confirm
      post :resend
    end
  end

  match "/google-auth/success",
        to: "users/omniauth_callbacks#google_oauth2",
        via: %i[get post],
        as: :google_oauth2_callback

  get "up" => "rails/health#show", as: :rails_health_check

  scope module: :public, as: :public do
    resources :clubs, only: %i[index show], path: "clubs"
  end

  namespace :club do
    resource :dashboard, only: :show

    resources :members do
      resources :consents, only: %i[index new create]
    end

    resources :consent_types, only: :index

    resources :invoices, only: %i[index show] do
      post :pay, on: :member
      get :download, on: :member
    end

    resources :teams do
      get :squad, on: :member
      get :match_sheet, on: :member
      resources :fixtures, only: %i[index create]
    end

    resources :fixtures, only: %i[show update] do
      patch :availability, on: :member
    end

    resources :broadcasts, only: %i[index new create show]

    resources :reports, only: :index do
      collection do
        get :finance
        get :participation
        get :compliance
        get :ar_aging
      end
    end
    resources :plans, only: :index
    root "dashboard"
  end

  namespace :admin do
    mount Sidekiq::Web => "/sidekiq" # access it at http://localhost:3000/sidekiq
    resource :dashboard, only: :show
    resources :clubs do
      post :impersonate, on: :member
      patch :remove_file, on: :member
      resources :membership_types,
                module: :clubs,
                except: %i[index] do
        resources :price_tiers,
                  module: :membership_types,
                  except: %i[index show]
      end
      resources :default_price_tiers,
                module: :clubs,
                except: %i[index]
      resources :membership_questions,
                module: :clubs,
                except: %i[index]
      resources :medical_questions,
                module: :clubs,
                except: %i[index] do
        patch :toggle, on: :member
      end
      resources :terms,
                module: :clubs,
                except: %i[index]
      resources :staggered_payment_plans,
                module: :clubs,
                except: %i[index show]
      resources :memberships,
                module: :clubs,
                only: %i[index show]
    end
    resources :users
    resources :members, only: %i[index show]
    resources :orders, only: %i[index show]

    resources :invoices, only: %i[index show] do
      collection { get :reconciliation }
    end

    resources :broadcasts, only: %i[index show update] do
      post :approve, on: :member
    end

    resources :audits, only: :index
    resources :retention_jobs, only: %i[index create]

    namespace :webhooks do
      resources :payments, only: :create
      resources :whatsapp, only: :create
    end

    root "dashboard"
  end

  namespace :members do
    resource :selection, only: :new do
      get :search
    end
    resource :dashboards
    get "" => "dashboards#index"
    resource :membership_registration, only: %i[show update]
    resource :cart, only: :show do
      resources :items, controller: "cart_items", only: %i[create update destroy]
    end
    resource :checkout, only: :create
    resources :payment_methods, only: :destroy
    resources :orders, only: :show
    get "checkout/success", to: "checkouts#success", as: :checkout_success
    get "checkout/failure", to: "checkouts#failure", as: :checkout_failure
  end

  root "members/dashboards#index"
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

class Admin::UsersController < Admin::BaseController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @super_admins = User.where(staff: true).order(:email)
    @users = User.where(staff: false).order(:email)
  end

  def show
    @club_roles = @user.club_roles.includes(:club)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.skip_terms_validation = true
    if @user.save
      redirect_to admin_user_path(@user), notice: "User created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    attributes = user_params.dup
    @user.skip_terms_validation = true
    if attributes[:password].blank?
      attributes.delete(:password)
      attributes.delete(:password_confirmation)
    end

    if @user.update(attributes)
      redirect_to admin_user_path(@user), notice: "User updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path, notice: "User deleted."
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :country_code, :mobile_number,
                                 :password, :password_confirmation, :staff, :role)
  end
end

app/controllers/users/mobile_verifications_controller.rb
# frozen_string_literal: true

class Users::MobileVerificationsController < ApplicationController
  before_action :authenticate_user!
  before_action :redirect_if_not_required, only: %i[new create verify confirm resend]
  before_action :ensure_verification_session, only: %i[verify confirm resend]

  def new
    @form = MobileVerificationForm.new(user: current_user)
  end

  def create
    @form = MobileVerificationForm.new(user: current_user)

    if @form.submit(mobile_verification_params.to_h)
      current_user.initiate_mobile_verification!
      redirect_to verify_users_mobile_verification_path,
                  notice: "We sent you a verification code. Please enter it below to confirm your number."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def verify
  end

  def confirm
    submitted_code = params.dig(:mobile_verification, :code).to_s.gsub(/\D+/, "")
    submitted_code = submitted_code[0, User::MOBILE_VERIFICATION_CODE_LENGTH] if submitted_code.present?

    if submitted_code.blank?
      flash.now[:alert] = "Please enter the verification code we sent to your phone."
      render :verify, status: :unprocessable_entity and return
    end

    if current_user.verify_mobile_code(submitted_code)
      redirect_to consume_post_mobile_capture_path(default_after_mobile_path),
                  notice: "Your mobile number is verified. Thank you!"
    else
      flash.now[:alert] = "That code was invalid or has expired. Please try again."
      render :verify, status: :unprocessable_entity
    end
  end

  def resend
    current_user.initiate_mobile_verification!
    redirect_to verify_users_mobile_verification_path,
                notice: "We sent you a new verification code."
  end

  private

  def mobile_verification_params
    params.require(:mobile_verification).permit(:country_code, :mobile_number)
  end

  def redirect_if_not_required
    return if current_user.mobile_details_missing?
    return if current_user.mobile_verification_code_digest.present?

    redirect_to consume_post_mobile_capture_path(default_after_mobile_path)
  end

  def ensure_verification_session
    if current_user.mobile_verification_code_digest.blank?
      current_user.initiate_mobile_verification!
    elsif current_user.mobile_verification_expired?
      current_user.initiate_mobile_verification!
      flash[:notice] = "We sent you a fresh verification code because the previous one expired."
    end
  end

  def default_after_mobile_path
    stored_location_for(current_user) || default_signed_in_path_for(current_user)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    auth = request.env["omniauth.auth"]
    club_id = oauth_params["club_id"].presence

    @user = User.from_omniauth(auth)
    sign_in(@user)
    set_flash_message!(:notice, :success, kind: "Google") if is_navigational_format?

    redirect_path = redirect_path_for(@user, club_id)

    respond_to do |format|
      format.html { redirect_to redirect_path }
      format.turbo_stream { redirect_to redirect_path, status: :see_other }
    end
  rescue ActiveRecord::RecordInvalid => e
    session["devise.google_data"] = auth.except("extra") if defined?(auth) && auth.present?
    redirect_to new_user_registration_path(club_id: club_id),
                alert: e.record.errors.full_messages.to_sentence
  end

  def failure
    redirect_to new_user_session_path, alert: "Google sign in failed. Please try again or use your email and password."
  end

  private

  def oauth_params
    request.env.fetch("omniauth.params", {}).with_indifferent_access
  end

  def redirect_path_for(user, club_id)
    return membership_registration_path_for(user, club_id) if club_id.present?

    stored_location_for(user) || default_redirect_for(user)
  end

  def membership_registration_path_for(user, club_id)
    store_registration_club(user, club_id)
    main_app.members_membership_registration_path(
      step: Members::MembershipRegistrationsController::STEPS.first,
      club_id: club_id
    )
  end

  def default_redirect_for(user)
    if user.respond_to?(:staff?) && user.staff?
      main_app.admin_dashboard_path
    elsif user.respond_to?(:club_roles) && user.club_roles.exists?
      main_app.club_root_path
    else
      main_app.members_path
    end
  end

  def store_registration_club(user, club_id)
    return unless club_id.present?

    session[:membership_registration] ||= {}
    user_key = "user_#{user.id}"
    session[:membership_registration][user_key] ||= {}
    session[:membership_registration][user_key][:club_id] = club_id
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  before_action :set_club
  before_action :ensure_mobile_reset_session!, only: %i[verify_mobile confirm_mobile resend_mobile]
  skip_before_action :verify_authenticity_token, only: :confirm_mobile

  def new
    self.resource = resource_class.new
    @mobile_password_reset_form = MobilePasswordResetRequestForm.new
    respond_with(resource)
  end

  def create
    if mobile_reset_request?
      handle_mobile_reset_request
    else
      @mobile_password_reset_form = MobilePasswordResetRequestForm.new
      super
    end
  end

  def verify_mobile
    @mobile_password_reset_verification_form = MobilePasswordResetVerificationForm.new
    @mobile_reset_number = mobile_reset_number_for_display
  end

  def confirm_mobile
    @mobile_password_reset_verification_form =
      MobilePasswordResetVerificationForm.new(mobile_verification_params)
    @mobile_reset_number = mobile_reset_number_for_display

    if @mobile_password_reset_verification_form.valid?
      user = mobile_reset_user
      sanitized_code = @mobile_password_reset_verification_form.sanitized_code

      if sanitized_code.present? && (token = user.consume_mobile_password_reset_code!(sanitized_code))
        session.delete(:mobile_password_reset)
        redirect_to edit_user_password_path(reset_password_token: token),
                    notice: "Code confirmed. You can now reset your password."
      else
        flash.now[:alert] = "That code was invalid or has expired. Please try again."
        render :verify_mobile, status: :unprocessable_entity
      end
    else
      flash.now[:alert] = "Please enter the verification code we sent to your phone."
      render :verify_mobile, status: :unprocessable_entity
    end
  end

  def resend_mobile
    user = mobile_reset_user
    user.initiate_mobile_password_reset!(club: @club)
    redirect_to verify_user_password_mobile_path(club_id: @club&.to_param),
                notice: "We sent you a new verification code."
  rescue StandardError => error
    Rails.logger.error("[MobilePasswordReset] Failed to resend code: #{error.class} #{error.message}")
    redirect_to verify_user_password_mobile_path(club_id: @club&.to_param),
                alert: "We couldn't resend the code right now. Please try again shortly."
  end

  private

  def set_club
    club_param = params[:club_id].presence || session.dig(:mobile_password_reset, "club_id")
    @club = Club.find_by_param(club_param) if club_param.present?
  end

  def mobile_reset_request?
    params[:reset_method] == "mobile"
  end

  def handle_mobile_reset_request
    @mobile_password_reset_form = MobilePasswordResetRequestForm.new(mobile_reset_params)
    self.resource = resource_class.new

    if @mobile_password_reset_form.valid?
      user = find_user_for_mobile_reset

      if user
        user.initiate_mobile_password_reset!(club: @club)
        session[:mobile_password_reset] = {
          "user_id" => user.id,
          "country_code" => @mobile_password_reset_form.normalized_country_code,
          "mobile_number" => @mobile_password_reset_form.normalized_mobile_number,
          "club_id" => @club&.to_param
        }
        redirect_to verify_user_password_mobile_path(club_id: @club&.to_param),
                    notice: "We sent you a verification code. Enter it below to continue."
      else
        @mobile_password_reset_form.errors.add(:base, "We couldn't find an account with that mobile number.")
        respond_with_navigational(resource) { render :new, status: :unprocessable_entity }
      end
    else
      respond_with_navigational(resource) { render :new, status: :unprocessable_entity }
    end
  rescue StandardError => error
    Rails.logger.error("[MobilePasswordReset] Failed to initiate reset: #{error.class} #{error.message}")
    flash.now[:alert] = "We couldn't start the password reset right now. Please try again."
    respond_with_navigational(resource) { render :new, status: :unprocessable_entity }
  end

  def find_user_for_mobile_reset
    resource_class.find_by(
      country_code: @mobile_password_reset_form.normalized_country_code,
      mobile_number: @mobile_password_reset_form.normalized_mobile_number
    )
  end

  def ensure_mobile_reset_session!
    unless mobile_reset_user
      session.delete(:mobile_password_reset)
      redirect_to new_user_password_path(club_id: @club&.to_param),
                  alert: "Please start the password reset process again." and return
    end
  end

  def mobile_reset_session
    session[:mobile_password_reset] || {}
  end

  def mobile_reset_user
    user_id = mobile_reset_session["user_id"]
    return nil if user_id.blank?

    @mobile_reset_user ||= resource_class.find_by(id: user_id)
  end

  def mobile_reset_number_for_display
    mobile_number = mobile_reset_session["mobile_number"]

    if mobile_number.present?
      mobile_number
    else
      nil
    end
  end

  def mobile_reset_params
    params.require(:mobile_password_reset).permit(:country_code, :mobile_number)
  end

  def mobile_verification_params
    params.require(:mobile_password_reset_verification).permit(:code)
  end
end

app/views/users/mobile_verifications/new.html.erb
<% content_for :title, "Add your mobile number" %>
<div class="h-[100vh] flex items-center px-3">
  <%= render 'shared/half_moon_header' %>
  <section class="mx-auto max-w-xl rounded-3xl border border-slate-200 bg-white p-8 shadow-sm">
    <h1 class="text-2xl font-semibold text-slate-900">We need your mobile number</h1>
    <p class="mt-2 text-sm text-slate-600">
      Please provide your mobile number so we can keep your account secure and share important membership updates.
      We&apos;ll text you a verification code right away.
    </p>

    <% if @form.errors.any? %>
      <div class="mt-4 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
        <p class="font-medium">We couldn&apos;t save those details:</p>
        <ul class="mt-2 list-disc space-y-1 pl-5">
          <% @form.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_with url: users_mobile_verification_path, scope: :mobile_verification, class: "mt-6 space-y-5" do |f| %>
      <div class="flex gap-3 flex-row">
        <div class="md:w-30" data-controller="country-code-selector"
            data-country-code-selector-initial-value="<%= @form.country_code.presence || '+27' %>">
          <%= f.hidden_field :country_code,
                            value: @form.country_code,
                            data: { country_code_selector_target: "input" } %>
          <button type="button"
                  class="flex w-full items-center justify-between rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-medium text-slate-700 shadow-sm focus:border-sky-400 focus:outline-none focus:ring-2 focus:ring-sky-200"
                  data-country-code-selector-target="button"
                  data-action="country-code-selector#open">
            <span data-country-code-selector-target="buttonLabel" class="flex w-full items-center justify-between"></span>
          </button>

          <div class="fixed inset-0 z-50 hidden items-start justify-center bg-slate-900/50 px-4 py-16"
              data-country-code-selector-target="overlay"
              data-action="click->country-code-selector#overlayClick">
            <div class="w-full max-w-md rounded-3xl bg-white shadow-xl ring-1 ring-slate-200"
                data-country-code-selector-target="dialog">
              <div class="flex items-center justify-between border-b border-slate-200 px-5 py-4">
                <h2 class="text-sm font-semibold text-slate-900">Select country code</h2>
                <button type="button"
                        class="rounded-full p-2 text-slate-500 hover:bg-slate-100 hover:text-slate-700 focus:outline-none focus:ring-2 focus:ring-sky-200"
                        data-action="country-code-selector#close">
                  <span aria-hidden="true">&times;</span>
                  <span class="sr-only">Close</span>
                </button>
              </div>
              <div class="px-5 py-4">
                <input type="search"
                      placeholder="Search country or code"
                      aria-label="Search country or dial code"
                      class="w-full rounded-xl border border-slate-200 px-3 py-2 text-sm focus:border-sky-400 focus:outline-none focus:ring-2 focus:ring-sky-200"
                      data-country-code-selector-target="search"
                      data-action="input->country-code-selector#filter">
              </div>
              <div class="max-h-80 overflow-y-auto" data-country-code-selector-target="list"></div>
            </div>
          </div>
        </div>

        <div class="flex-1"
            data-controller="mobile-number"
            data-mobile-number-code-value="<%= @form.country_code.presence || '+27' %>"
            data-mobile-number-country-input-value="mobile_verification_country_code">
          <%= f.label :mobile_number, "Mobile number", class: "sr-only" %>
          <%= f.telephone_field :mobile_number,
                                value: @form.mobile_number,
                                autocomplete: "tel-national",
                                placeholder: "Mobile number",
                                class: "block w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-900 placeholder-slate-400 focus:border-sky-400 focus:outline-none focus:ring-2 focus:ring-sky-200",
                                data: { mobile_number_target: "input" } %>
        </div>
      </div>

      <div class="pt-2">
        <%= f.submit "Send verification code",
                    class: "w-full rounded-2xl bg-sky-500 px-4 py-3 text-sm font-semibold uppercase tracking-wide text-white shadow-lg transition hover:bg-sky-600 focus:outline-none focus:ring-2 focus:ring-sky-300" %>
      </div>
    <% end %>
  </section>
</div>

app/views/users/mobile_verifications/verify.html.erb
<% content_for :title, "Verify your mobile number" %>

<section class="mx-auto max-w-xl rounded-3xl border border-slate-200 bg-white p-8 shadow-sm">
  <h1 class="text-2xl font-semibold text-slate-900">Enter your verification code</h1>
  <p class="mt-2 text-sm text-slate-600">
    We sent a 6-digit code to <span class="font-medium text-slate-900">+<%= current_user.formatted_mobile_number %></span>.
    Enter it below to confirm your mobile number.
  </p>

  <%= form_with url: confirm_users_mobile_verification_path, scope: :mobile_verification, class: "mt-6 space-y-5" do |f| %>
    <div>
      <%= f.label :code, "Verification code", class: "sr-only" %>
      <%= f.text_field :code,
                       inputmode: "numeric",
                       autocomplete: "one-time-code",
                       placeholder: "123456",
                       maxlength: 6,
                       class: "block w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-center text-2xl tracking-widest text-slate-900 focus:border-sky-400 focus:outline-none focus:ring-2 focus:ring-sky-200" %>
    </div>

    <div class="space-y-3">
      <%= f.submit "Verify number",
                   class: "w-full rounded-2xl bg-sky-500 px-4 py-3 text-sm font-semibold uppercase tracking-wide text-white shadow-lg transition hover:bg-sky-600 focus:outline-none focus:ring-2 focus:ring-sky-300" %>

      <%= link_to "Resend code",
                  resend_users_mobile_verification_path,
                  data: { turbo_method: :post },
                  class: "block w-full rounded-2xl border border-slate-200 px-4 py-3 text-center text-sm font-semibold text-slate-700 transition hover:bg-slate-50 focus:outline-none focus:ring-2 focus:ring-sky-200" %>
    </div>
  <% end %>
</section>